package org.usfirst.frc.team1089.auton;

public enum PosEnum {
	POS1,
	POS2_LEFT_PATH,
	POS2_CENTER_PATH,
	POS2_BACKWARD_PATH,
	POS3,
	POS4,
	POS5_HAILMARY,
	POS5_CENTER_PATH,
	POS5_RIGHT_PATH, 
	POS5_SECRET_PATH,
	POS5_BACKWARD_PATH,
	SPYBOT,
}
